### ISSUE TITLE
偽SiReFaSo/偽SoSiReMiへの掲載検討（トピックつけるだけ）

### ISSUE THREAD

**Issue by ponapalt** [ambergon/UkagakaPlugin_DBdiary#1]
差し支えなければ、偽SiReFaSo/偽SoSiReMiのリストへの掲載を検討してください。
トピック（タグっぽいもの）をつけるだけです。

https://nikolat.github.io/sosiremi/about.html

https://nikolat.github.io/sirefaso/about.html

https://docs.github.com/ja/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by ambergon** [comment]
対応しました。
